### ISSUE TITLE
error in downstream_imagenet

### ISSUE THREAD

**Issue by alskdjfasdfsadf** [keyu-tian/SparK#34]
Thanks for your great work! however, in downstream_imagenet, I found an error.
I used the code '~/SparK/downstream_imagenet$ bash ./main.sh exp1 --data_path=/home/users/data --model=resnet50 --resume_from=/home/users/SparK/pretrain/output/resnet50_1kpretrained.pth  --bs=32'

and the following error happened: 
[05-17 12:28:48] (nstream_imagenet/main.py, line  49)=> [FT start] from ep0
[05-17 12:28:48] (nstream_imagenet/main.py, line  58)=> [loader_train.sampler.set_epoch(0)]
Traceback (most recent call last):
  File "/home/users/SparK/downstream_imagenet/main.py", line 189, in <module>
    main_ft()
  File "/home/users/SparK/downstream_imagenet/main.py", line 60, in main_ft
    train_loss, train_acc = fine_tune_one_epoch(ep, args, tb_lg, loader_train, iters_train, criterion, mixup_fn, model, model_ema, optimizer, params_req_grad)
  File "/home/users/SparK/downstream_imagenet/main.py", line 129, in fine_tune_one_epoch
    inp, tar = mixup_fn(inp, tar)
ValueError: too many values to unpack (expected 2)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=3 encoding='UTF-8'>
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3006233) of binary: /usr/bin/python3

**Comment by keyu-tian** [comment]
Thanks and i fixed it in the latest commit.
